# Configuration for CircleCI
# https://circleci.com/gh/tony19/apktool-lib
version: 2.0

jobs:
  build:
    branches:
      ignore: gh-pages
    working_directory: ~/code
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "apktool-lib/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "apktool-lib/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew check assembleDebug assembleRelease --parallel
      - store_artifacts:
          path: apktool-lib/build/reports
          destination: reports
      - store_artifacts:
          path: apktool-lib/build/outputs
          destination: outputs
      - store_test_results:
          path: apktool-lib/build/test-results
      - run:
          name: Deploy snapshot
          command: scripts/deploysnapshot.sh
